PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS version (
  `key` VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS categories (
  id INTEGER PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO categories (name) VALUES ('Bäcker');
INSERT INTO categories (name) VALUES ('Mittag');

CREATE TABLE IF NOT EXISTS budget (
  id INTEGER PRIMARY KEY,
  category_id INTEGER NOT NULL,
  `type` VARCHAR(255) NOT NULL DEFAULT 'spend',
  `date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  amount DECIMAL(15,2) NOT NULL,
  `special` INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
);

INSERT INTO `version` VALUES ('20150221130000');