import:
    - "%root_dir%/app/parameters.yml"

debug: true
mode: "development"

# Paths
app_dir:        "%root_dir%/app"
data_dir:       "%root_dir%/data"
cache_dir:      "%data_dir%/cache"

# Logging
log.enabled: true
log.level:   8
log_dir:     "%data_dir%/log"

migration_dir: "%app_dir%/migrations"

routes:
    - "Nogo\\Api\\Controller\\ResourceController"
    - "Nogo\\Budget\\Controller\\AppController"

api:
    prefix: "/api"
    version: 1
    headers:
      Content-Type: "application/json; charset=utf-8"
      Access-Control-Allow-Origin: "*"
      Access-Control-Allow-Credentials: "true"
      Access-Control-Allow-Methods: "GET,POST,PUT,DELETE"
    resources:
        budget:
            model: "Nogo\\Budget\\Model\\Budget"
        categories:
            model: "Nogo\\Budget\\Model\\Category"